server:
  servlet:
    context-path: '/drug_finder/v1/'

spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/v2_drug'
    username: 'newuser'
    password: 'password'
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret: hgjfvbjlyfgjhbjkyutfhgvbnmhjgyturfgdhvhjkuyturyfghjgfh
